<!DOCTYPE html>
<html>
<head>
	<title>Rincian Pengajuan Ijin Dinas</title>
</head>
<body>

	<h3>Kepada ${name},</h3>

	<p>Pengajuan Ijin Dinas anda berhasil disetujui</p>
	<p>Berikut rincian data yang kami sepakati</p>
	
	<br/>

	<p><b>Tujuan Dinas : </b>${tujuandinas}</p> 
	<p><b>Kendaraan :</b>${kendaraan}</p> 
	<p><b>Kota Asal Keberangkatan :</b> ${kotaasal}</p> 
	<p><b>Kota Tujuan Keberangkatan :</b>${kotatujuan}</p> 
	<p><b>Waktu Berangkat :</b>${waktuberangkat}</p> 
	<p><b>Waktu Pulang :</b>${waktupulang}</p> 
	<p><b>Tanggal Berangkat :</b>${tanggalberangkat}</p> 
	<p><b>Tanggal Pulang :</b>${tanggalpulang}</p> 
	<p><b>Hotel :</b>${hotel}</p>
	<p><b>Total Diema :</b>${diem}</p> 

	<br/>

	<p>Terima Kasih</p>

</body>
</html>